export interface ChecklistControl {
  id: string
  title: string
  category: string
  configPath: string
  severity: 'critical' | 'high' | 'medium' | 'low'
  risk: string
  recommendation: string
  check: string
  auditCheckId?: string
  docRef: string
  options?: {
    values: (string | boolean)[]
    recommended: string | boolean
  }
}

export interface ChecklistCategory {
  id: string
  title: string
  ring: string
  riskTheme: string
}

export const categories: ChecklistCategory[] = [
  { id: 'gateway', title: 'Gateway Authentication', ring: 'Gateway', riskTheme: 'Unauthenticated access, brute force' },
  { id: 'network', title: 'Network Exposure', ring: 'Gateway', riskTheme: 'Information disclosure, MITM, public exposure' },
  { id: 'device', title: 'Device Identity & Pairing', ring: 'Gateway', riskTheme: 'Impersonation, replay attacks' },
  { id: 'sessions', title: 'Session Isolation', ring: 'Sessions', riskTheme: 'Cross-user context leakage' },
  { id: 'channels', title: 'Channel Access Control', ring: 'Sessions', riskTheme: 'Unauthorized messaging, spam, command abuse' },
  { id: 'tools', title: 'Tool Policy', ring: 'Tools', riskTheme: 'Unintended tool access, privilege escalation' },
  { id: 'exec', title: 'Shell Execution', ring: 'Tools', riskTheme: 'Remote code execution' },
  { id: 'sandbox', title: 'Docker Sandboxing', ring: 'Sandbox', riskTheme: 'Container escape, resource exhaustion' },
  { id: 'elevated', title: 'Elevated Mode', ring: 'Sandbox', riskTheme: 'Host escape, sandbox bypass' },
  { id: 'hooks', title: 'Hooks & Webhooks', ring: 'Gateway', riskTheme: 'Session injection, prompt injection, token reuse' },
  { id: 'plugins', title: 'Plugins & Extensions', ring: 'Tools', riskTheme: 'Supply chain, in-process compromise' },
  { id: 'credentials', title: 'Credentials & Secrets', ring: 'Host', riskTheme: 'Credential exposure, log leakage' },
  { id: 'agent', title: 'Agent Configuration', ring: 'Model', riskTheme: 'Prompt injection, PII exposure, model downgrade' },
]

export const controls: ChecklistControl[] = [
  // ═══════════════════════════════════════════
  // Gateway Authentication
  // ═══════════════════════════════════════════
  {
    id: 'gw-1',
    title: 'Authentication Mode',
    category: 'gateway',
    configPath: 'gateway.auth.mode',
    severity: 'critical',
    risk: 'Without authentication, any network client can connect to the gateway and interact with the agent, enabling remote code execution via tool invocation.',
    recommendation: "Set to 'token' with a 48+ hex char random token. Never use 'none' in production.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "gateway.http.no_auth")\'',
    auditCheckId: 'gateway.http.no_auth',
    docRef: '/access-control#_1-1-auth-modes',
    options: { values: ['token', 'password', 'trusted-proxy', 'none'], recommended: 'token' },
  },
  {
    id: 'gw-2',
    title: 'Auth Token Strength',
    category: 'gateway',
    configPath: 'gateway.auth.token',
    severity: 'high',
    risk: 'A short or low-entropy token is vulnerable to brute-force attacks. Timing-safe comparison prevents timing side-channels but does not compensate for weak tokens.',
    recommendation: 'Use the auto-generated 48-hex-char token or supply a custom token of at least 48 hex characters (24 random bytes). Supply via OPENCLAW_GATEWAY_TOKEN env var.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "gateway.token_too_short")\'',
    auditCheckId: 'gateway.token_too_short',
    docRef: '/access-control#_1-1-1-token-auth',
  },
  {
    id: 'gw-3',
    title: 'Password Auth',
    category: 'gateway',
    configPath: 'gateway.auth.password',
    severity: 'high',
    risk: 'A weak password exposes the gateway to brute-force attacks. Password auth is required for Tailscale Funnel but uses the same timing-safe SHA-256 comparison as token auth.',
    recommendation: 'Use a strong, unique password. Supply via OPENCLAW_GATEWAY_PASSWORD env var rather than the config file.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "config.secrets.gateway_password_in_config")\'',
    auditCheckId: 'config.secrets.gateway_password_in_config',
    docRef: '/access-control#_1-1-2-password-auth',
  },
  {
    id: 'gw-4',
    title: 'Network Bind Mode',
    category: 'gateway',
    configPath: 'gateway.bind',
    severity: 'critical',
    risk: 'Binding to a non-loopback address without authentication exposes the gateway to all hosts on the network. Any client that can reach the port can interact with the agent.',
    recommendation: "Set to 'loopback' for local-only. Use 'tailnet' for remote via Tailscale. Never use 'lan' without auth.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "gateway.bind_no_auth")\'',
    auditCheckId: 'gateway.bind_no_auth',
    docRef: '/network-security#bind-modes',
    options: { values: ['loopback', 'lan', 'tailnet', 'auto', 'custom'], recommended: 'loopback' },
  },
  {
    id: 'gw-5',
    title: 'Rate Limiting',
    category: 'gateway',
    configPath: 'gateway.auth.rateLimit',
    severity: 'high',
    risk: 'Without rate limiting, attackers can attempt unlimited authentication guesses. The in-memory sliding window is the only brute-force protection for the shared-secret auth path.',
    recommendation: 'Configure maxAttempts: 10, windowMs: 60000, lockoutMs: 300000. Rate limiting is NOT enabled by default.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "gateway.auth_no_rate_limit")\'',
    auditCheckId: 'gateway.auth_no_rate_limit',
    docRef: '/access-control#_1-8-rate-limiting',
  },
  {
    id: 'gw-6',
    title: 'Control UI Device Auth',
    category: 'gateway',
    configPath: 'gateway.controlUi.dangerouslyDisableDeviceAuth',
    severity: 'critical',
    risk: 'Disabling device auth removes Ed25519 challenge-response verification. Any client with the shared secret can operate the gateway without proving device identity.',
    recommendation: 'Keep set to false. This flag exists only for local development. Never disable in production.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "gateway.control_ui.device_auth_disabled")\'',
    auditCheckId: 'gateway.control_ui.device_auth_disabled',
    docRef: '/access-control#_1-6-device-identity-and-pairing',
  },
  {
    id: 'gw-7',
    title: 'Insecure Auth Compatibility',
    category: 'gateway',
    configPath: 'gateway.controlUi.allowInsecureAuth',
    severity: 'medium',
    risk: 'Allows authentication without device identity verification. While restricted to localhost, it weakens defense-in-depth by removing the cryptographic identity layer.',
    recommendation: 'Keep set to false. Use full device identity verification even for local connections.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "gateway.control_ui.insecure_auth")\'',
    auditCheckId: 'gateway.control_ui.insecure_auth',
    docRef: '/access-control#_1-5-auth-mode-resolution-priority',
  },
  {
    id: 'gw-8',
    title: 'Trusted Proxy Configuration',
    category: 'gateway',
    configPath: 'gateway.auth.trustedProxies',
    severity: 'critical',
    risk: 'Misconfigured trusted proxies allow IP spoofing via X-Forwarded-For headers. Using trusted-proxy mode without a proxies list means any request with the right headers is accepted.',
    recommendation: 'Set trustedProxies to explicit CIDR ranges, configure requiredHeaders, set userHeader, and define allowUsers.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "gateway.trusted_proxy_no_proxies")\'',
    auditCheckId: 'gateway.trusted_proxy_no_proxies',
    docRef: '/network-security#trusted-proxy-configuration',
  },

  // ═══════════════════════════════════════════
  // Network Exposure
  // ═══════════════════════════════════════════
  {
    id: 'net-1',
    title: 'TLS Enforcement',
    category: 'network',
    configPath: '(hardcoded)',
    severity: 'high',
    risk: 'Without TLS, all gateway traffic including auth tokens and session data is transmitted in cleartext. Man-in-the-middle attacks can intercept or modify any communication.',
    recommendation: 'TLS 1.3 is enforced automatically. Replace the auto-generated self-signed certificate with a CA-signed certificate for production.',
    check: 'openssl s_client -connect <host>:<port> 2>/dev/null | grep Protocol',
    docRef: '/network-security#_2-tls',
  },
  {
    id: 'net-2',
    title: 'mDNS Discovery Mode',
    category: 'network',
    configPath: 'discovery.mdns.mode',
    severity: 'medium',
    risk: "Full mDNS broadcasts gateway IP, port, TLS status, Tailnet DNS name, cliPath, and sshPort to every device on the local network.",
    recommendation: "Set to 'off' in production or 'minimal' at most.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "discovery.mdns_full_mode")\'',
    auditCheckId: 'discovery.mdns_full_mode',
    docRef: '/network-security#discovery-modes',
    options: { values: ['off', 'minimal', 'full'], recommended: 'off' },
  },
  {
    id: 'net-3',
    title: 'mDNS Kill Switch',
    category: 'network',
    configPath: 'OPENCLAW_DISABLE_BONJOUR',
    severity: 'medium',
    risk: 'Even with discovery.mdns.mode off, a config change could re-enable broadcasting. The env var kill switch cannot be overridden by config.',
    recommendation: 'Set OPENCLAW_DISABLE_BONJOUR=1 in the environment for production deployments.',
    check: 'echo $OPENCLAW_DISABLE_BONJOUR  # should output 1',
    docRef: '/network-security#kill-switch',
  },
  {
    id: 'net-4',
    title: 'Wide-Area DNS-SD',
    category: 'network',
    configPath: 'discovery.wideArea.enabled',
    severity: 'medium',
    risk: 'Wide-area DNS-SD advertises the gateway over unicast DNS within the Tailnet, making it findable by any device on the Tailnet.',
    recommendation: 'Keep set to false unless Tailnet-wide service discovery is explicitly required.',
    check: 'Verify discovery.wideArea.enabled is false in openclaw.json',
    docRef: '/network-security#wide-area-dns-sd',
  },
  {
    id: 'net-5',
    title: 'Security Headers (HSTS)',
    category: 'network',
    configPath: 'gateway.http.securityHeaders.strictTransportSecurity',
    severity: 'high',
    risk: 'HSTS is NOT automatically enabled even when TLS is active. Without HSTS, browsers may allow downgrade to HTTP, exposing credentials to interception.',
    recommendation: 'Explicitly configure strictTransportSecurity with an appropriate max-age. Default headers only include X-Content-Type-Options and Referrer-Policy.',
    check: 'curl -sI https://<host>:<port>/ | grep -i strict-transport-security',
    docRef: '/network-security#security-headers',
  },
  {
    id: 'net-6',
    title: 'Tailscale Mode',
    category: 'network',
    configPath: 'tailscale.mode',
    severity: 'high',
    risk: 'Tailscale Funnel exposes the gateway to the public internet. Serve mode is Tailnet-scoped but still expands the attack surface beyond loopback.',
    recommendation: "Use 'serve' for Tailnet-only remote access. Avoid 'funnel' unless password auth is enforced.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "gateway.tailscale_funnel")\'',
    auditCheckId: 'gateway.tailscale_funnel',
    docRef: '/access-control#_1-2-tailscale-identity-auth-implicit',
    options: { values: ['off', 'serve', 'funnel'], recommended: 'off' },
  },
  {
    id: 'net-7',
    title: 'Certificate Pinning',
    category: 'network',
    configPath: 'gateway.remote.tlsFingerprint',
    severity: 'medium',
    risk: 'Without certificate pinning, remote clients accept any valid TLS certificate for the gateway. A compromised CA could allow MITM attacks.',
    recommendation: 'Set gateway.remote.tlsFingerprint to the SHA-256 fingerprint of the gateway TLS certificate.',
    check: 'openssl s_client -connect <host>:<port> 2>/dev/null | openssl x509 -fingerprint -sha256 -noout',
    docRef: '/network-security#certificate-pinning',
  },

  // ═══════════════════════════════════════════
  // Device Identity & Pairing
  // ═══════════════════════════════════════════
  {
    id: 'dev-1',
    title: 'Ed25519 Challenge-Response',
    category: 'device',
    configPath: '(hardcoded)',
    severity: 'critical',
    risk: 'If the Ed25519 challenge-response is bypassed (via dangerouslyDisableDeviceAuth), any client with the shared secret can operate the gateway without proving device identity.',
    recommendation: 'Never disable the challenge-response protocol in production. Enforces per-connection random nonce and +/- 2 minute timestamp skew.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "gateway.control_ui.device_auth_disabled")\'',
    auditCheckId: 'gateway.control_ui.device_auth_disabled',
    docRef: '/access-control#_1-6-device-identity-and-pairing',
  },
  {
    id: 'dev-2',
    title: 'Device Keypair Permissions',
    category: 'device',
    configPath: '~/.openclaw/identity/device.json',
    severity: 'critical',
    risk: 'The device keypair contains the Ed25519 private key. If readable by other users, any local user can impersonate the device and gain full authenticated access.',
    recommendation: "Ensure device.json has file mode 0o600. Run 'openclaw security audit --fix' to auto-remediate.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id | startswith("fs."))\'',
    auditCheckId: 'fs.state_dir.perms_world_writable',
    docRef: '/credentials-secrets#_2-file-permission-model',
  },
  {
    id: 'dev-3',
    title: 'Pairing Timeout and Caps',
    category: 'device',
    configPath: '(hardcoded)',
    severity: 'high',
    risk: 'Long-lived pairing windows increase the risk of unauthorized device enrollment. Without pending request caps, an attacker can flood the pairing system.',
    recommendation: 'Pairing requests expire after 5 minutes (hardcoded). Channel pairing codes expire after 1 hour with max 3 pending per channel. Review pending requests promptly.',
    check: 'Manual: verify pairing requests expire in the Control UI',
    docRef: '/access-control#_1-6-device-identity-and-pairing',
  },
  {
    id: 'dev-4',
    title: 'Scope Enforcement',
    category: 'device',
    configPath: '(hardcoded)',
    severity: 'critical',
    risk: 'Connections without verified device identity have all scopes stripped (default-deny). Bypassing scope enforcement allows unauthenticated access to admin-level methods.',
    recommendation: "Assign minimum necessary role: 'viewer' for monitoring, 'operator' for standard operations, 'admin' only for full control.",
    check: 'Manual: verify connections without device identity cannot invoke scope-guarded methods',
    docRef: '/access-control#_1-7-scope-enforcement',
  },
  {
    id: 'dev-5',
    title: 'Auto-Approval Rules',
    category: 'device',
    configPath: '(hardcoded)',
    severity: 'medium',
    risk: 'Loopback and same-Tailscale-node connections are auto-approved without manual pairing. If an attacker gains local access, they get a paired device identity automatically.',
    recommendation: 'Monitor the Control UI for unexpected pairing events. All remote connections require manual pairing approval.',
    check: 'Manual: verify remote connections require explicit pairing approval',
    docRef: '/access-control#_1-6-device-identity-and-pairing',
  },

  // ═══════════════════════════════════════════
  // Session Isolation
  // ═══════════════════════════════════════════
  {
    id: 'sess-1',
    title: 'DM Session Scope',
    category: 'sessions',
    configPath: 'session.dmScope',
    severity: 'high',
    risk: "Global session scope causes conversation context from one user to leak into another user's session, exposing tool outputs, conversation history, and potentially secrets.",
    recommendation: "Set to 'per-channel-peer' for isolated sessions per sender per channel.",
    check: "Verify session.dmScope in openclaw.json is not 'global'.",
    docRef: '/access-control#_2-3-session-isolation',
    options: { values: ['per-peer', 'per-channel-peer', 'per-account-channel-peer', 'global'], recommended: 'per-channel-peer' },
  },
  {
    id: 'sess-2',
    title: 'Identity Links Configuration',
    category: 'sessions',
    configPath: 'session.identityLinks',
    severity: 'medium',
    risk: 'Incorrect identity links can merge sessions of different people, causing cross-user context leakage.',
    recommendation: 'Only create identity links for verified same-person identifiers. Audit the map to ensure no two different people share a canonical name.',
    check: 'Review session.identityLinks in openclaw.json — confirm each canonical name maps to a single real person.',
    docRef: '/access-control#identity-links',
  },
  {
    id: 'sess-3',
    title: 'Session Key as Routing Only',
    category: 'sessions',
    configPath: '(implicit)',
    severity: 'medium',
    risk: 'If session keys were treated as auth boundaries, a caller who can guess or inject a session key could hijack ongoing conversations.',
    recommendation: 'Do not rely on session keys for authentication. Ensure gateway auth and channel access control are enforced before session routing.',
    check: 'Confirm hooks.allowRequestSessionKey is false.',
    docRef: '/access-control#_2-3-session-isolation',
  },
  {
    id: 'sess-4',
    title: 'Multi-Account Session Scope',
    category: 'sessions',
    configPath: 'session.dmScope',
    severity: 'high',
    risk: "When running multiple bot accounts on the same provider, 'per-channel-peer' can collide sessions across accounts, leaking context between bot personalities.",
    recommendation: "Set to 'per-account-channel-peer' when operating multiple bot accounts on the same provider.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id | contains("scope_main_multiuser"))\'',
    auditCheckId: 'channels.*.dm.scope_main_multiuser',
    docRef: '/access-control#_2-3-session-isolation',
  },

  // ═══════════════════════════════════════════
  // Channel Access Control
  // ═══════════════════════════════════════════
  {
    id: 'chan-1',
    title: 'DM Policy',
    category: 'channels',
    configPath: 'channels.<provider>.dmPolicy',
    severity: 'critical',
    risk: "An 'open' DM policy allows any sender on the platform to interact with the bot, exposing all enabled tools to arbitrary untrusted users.",
    recommendation: "Set to 'pairing' (challenge-code flow) or 'allowlist' (explicit sender IDs). Never use 'open' in production.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id | startswith("channels.") and contains("dm.open"))\'',
    auditCheckId: 'channels.*.dm.open',
    docRef: '/access-control#_2-1-dm-policies',
    options: { values: ['pairing', 'allowlist', 'open', 'disabled'], recommended: 'pairing' },
  },
  {
    id: 'chan-2',
    title: 'DM Allowlist',
    category: 'channels',
    configPath: 'channels.<provider>.allowFrom',
    severity: 'high',
    risk: "Without an explicit allowlist, the only gate is the DM policy. If changed to 'open' later, access control is effectively absent.",
    recommendation: "Populate allowFrom with explicit sender identifiers for each active provider.",
    check: 'Verify channels.<provider>.allowFrom in openclaw.json contains at least one sender identifier.',
    docRef: '/access-control#_2-1-dm-policies',
  },
  {
    id: 'chan-3',
    title: 'Group Policy',
    category: 'channels',
    configPath: 'channels.<provider>.groups.*.groupPolicy',
    severity: 'critical',
    risk: "An 'open' group policy allows every group member to interact with the bot. Combined with powerful tools, this creates an RCE vector via group membership.",
    recommendation: "Set to 'allowlist' and populate groupAllowFrom. Use 'disabled' for groups without bot access.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id | contains("security.exposure.open_groups"))\'',
    docRef: '/access-control#_2-2-group-policies',
    options: { values: ['allowlist', 'open', 'disabled'], recommended: 'allowlist' },
  },
  {
    id: 'chan-4',
    title: 'Group Mention Requirement',
    category: 'channels',
    configPath: 'channels.<provider>.groups.*.requireMention',
    severity: 'high',
    risk: 'Without requireMention, every message in the group triggers the bot, causing cost overruns and potential prompt injection from any member.',
    recommendation: 'Set requireMention to true for all groups.',
    check: 'Verify channels.<provider>.groups.*.requireMention is true in openclaw.json.',
    docRef: '/access-control#_2-2-group-policies',
  },
  {
    id: 'chan-5',
    title: 'Group AllowFrom',
    category: 'channels',
    configPath: 'channels.<provider>.groups.*.groupAllowFrom',
    severity: 'high',
    risk: "An empty or wildcard groupAllowFrom with groupPolicy 'allowlist' either blocks all senders or permits all, both likely misconfigurations.",
    recommendation: "Populate groupAllowFrom with specific sender identifiers when groupPolicy is 'allowlist'.",
    check: 'Verify channels.<provider>.groups.*.groupAllowFrom contains explicit sender IDs.',
    docRef: '/access-control#_2-2-group-policies',
  },
  {
    id: 'chan-6',
    title: 'Per-Sender Tool Policy in Groups',
    category: 'channels',
    configPath: 'channels.<provider>.groups.*.toolsBySender',
    severity: 'high',
    risk: 'Without per-sender tool restrictions, every allowed group member has access to the full tool set, including potentially dangerous tools.',
    recommendation: "Use toolsBySender with a restrictive wildcard default '*', then grant additional tools to trusted senders by ID.",
    check: 'Review toolsBySender in openclaw.json — verify the wildcard default is restrictive.',
    docRef: '/access-control#per-sender-tool-policies-in-groups',
  },
  {
    id: 'chan-7',
    title: 'Command Authorization',
    category: 'channels',
    configPath: 'commands.useAccessGroups',
    severity: 'critical',
    risk: 'When false, senders not in any allowlist can still execute slash commands, bypassing channel access control.',
    recommendation: 'Keep commands.useAccessGroups set to true (default).',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id | contains("useAccessGroups"))\'',
    auditCheckId: 'channels.slack.commands.slash.useAccessGroups_off',
    docRef: '/access-control#_2-4-command-authorization',
  },
  {
    id: 'chan-8',
    title: 'Pairing Code Properties',
    category: 'channels',
    configPath: '(hardcoded)',
    severity: 'medium',
    risk: 'Weak pairing codes allow brute-force or social engineering attacks that grant attacker access to the bot.',
    recommendation: "Pairing generates 8-char alphanumeric codes (excluding O/0/I/1) with 1-hour expiry and max 3 pending per channel. These are hardcoded.",
    check: "Verify dmPolicy is 'pairing' in openclaw.json.",
    docRef: '/access-control#pairing-codes',
  },

  // ═══════════════════════════════════════════
  // Tool Policy
  // ═══════════════════════════════════════════
  {
    id: 'tool-1',
    title: 'Tool Profile Selection',
    category: 'tools',
    configPath: 'tools.profile',
    severity: 'high',
    risk: "The 'full' profile imposes no tool restrictions, granting access to shell execution, gateway reconfiguration, and session manipulation.",
    recommendation: "Use 'messaging' for chat bots or 'minimal' for maximum restriction. Never use 'full' for untrusted users.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "tools.profile_minimal_overridden")\'',
    auditCheckId: 'tools.profile_minimal_overridden',
    docRef: '/tool-security#_1-tool-profiles',
    options: { values: ['minimal', 'coding', 'messaging', 'full'], recommended: 'messaging' },
  },
  {
    id: 'tool-2',
    title: 'Global Tool Allow List',
    category: 'tools',
    configPath: 'tools.allow',
    severity: 'medium',
    risk: 'Without a global allow list, the tool profile alone determines availability, which may be broader than intended.',
    recommendation: 'Define tools.allow with the minimum set of tools required. Use glob patterns for convenience.',
    check: 'Verify tools.allow in openclaw.json contains an explicit list of needed tools.',
    docRef: '/tool-security#_3-policy-pipeline-resolution-order',
  },
  {
    id: 'tool-3',
    title: 'Global Tool Deny List',
    category: 'tools',
    configPath: 'tools.deny',
    severity: 'high',
    risk: 'Without a deny list, dangerous tool groups (group:automation, group:runtime) remain available if the profile permits them.',
    recommendation: 'Deny dangerous groups: ["group:automation", "group:runtime", "group:fs", "sessions_spawn", "sessions_send"]. Deny always wins.',
    check: 'Verify tools.deny array in openclaw.json includes dangerous groups.',
    docRef: '/tool-security#_3-policy-pipeline-resolution-order',
  },
  {
    id: 'tool-4',
    title: 'Filesystem workspaceOnly',
    category: 'tools',
    configPath: 'tools.fs.workspaceOnly',
    severity: 'high',
    risk: 'When false, read/write/edit tools can access any file on the host filesystem, enabling path traversal to read secrets from /etc, ~/.ssh, or credential stores.',
    recommendation: 'Set to true to restrict filesystem tools to the workspace directory.',
    check: 'Verify tools.fs.workspaceOnly is true in openclaw.json.',
    docRef: '/tool-security#workspace-restrictions',
  },
  {
    id: 'tool-5',
    title: 'Per-Agent Tool Policy',
    category: 'tools',
    configPath: 'agents.<id>.tools.allow / agents.<id>.tools.deny',
    severity: 'high',
    risk: 'Without per-agent restrictions, all agents inherit the global tool policy. A public agent and trusted personal agent would have identical access.',
    recommendation: 'Define per-agent allow/deny lists. For untrusted-facing agents, deny filesystem, exec, and session manipulation tools.',
    check: 'Verify agents.<id>.tools in openclaw.json for each configured agent.',
    docRef: '/tool-security#_3-policy-pipeline-resolution-order',
  },
  {
    id: 'tool-6',
    title: 'Gateway HTTP Tool Restrictions',
    category: 'tools',
    configPath: 'gateway.tools.allow',
    severity: 'critical',
    risk: 'The HTTP tool invoke endpoint has a default deny list. Re-enabling blocked tools via gateway.tools.allow exposes RCE and message injection vectors over HTTP.',
    recommendation: 'Do not override the gateway HTTP tool deny list unless behind strong authentication.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "gateway.tools_invoke_http.dangerous_allow")\'',
    auditCheckId: 'gateway.tools_invoke_http.dangerous_allow',
    docRef: '/tool-security#_9-gateway-http-tool-deny-list',
  },
  {
    id: 'tool-7',
    title: 'Plugin Tool Group',
    category: 'tools',
    configPath: 'plugins.allow',
    severity: 'high',
    risk: 'Plugin tools run in-process with full gateway privileges. Their HTTP routes are NOT protected by gateway auth.',
    recommendation: 'Maintain an explicit plugins.allow list. Use plugins.deny to block specific plugins. Review plugin code before enabling.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "plugins.tools_reachable_permissive_policy")\'',
    auditCheckId: 'plugins.tools_reachable_permissive_policy',
    docRef: '/plugins-extensions#_2-plugin-allowlist',
  },

  // ═══════════════════════════════════════════
  // Shell Execution
  // ═══════════════════════════════════════════
  {
    id: 'exec-1',
    title: 'Exec Security Mode',
    category: 'exec',
    configPath: 'tools.exec.security',
    severity: 'critical',
    risk: "The 'full' security mode permits unrestricted shell command execution, allowing the model to run any command including data exfiltration or backdoor installation.",
    recommendation: "Set to 'deny' to block all shell execution, or 'allowlist' to permit only matched patterns. Never 'full' for untrusted users.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id | startswith("tools.exec.host_sandbox"))\'',
    auditCheckId: 'tools.exec.host_sandbox_no_sandbox_defaults',
    docRef: '/tool-security#security-modes',
    options: { values: ['deny', 'allowlist', 'full'], recommended: 'deny' },
  },
  {
    id: 'exec-2',
    title: 'Exec Approval Mode',
    category: 'exec',
    configPath: 'tools.exec.ask',
    severity: 'high',
    risk: "With ask mode 'off', shell commands execute without operator confirmation, removing the human-in-the-loop safety net.",
    recommendation: "Set to 'always' so every command requires approval. Use 'on-miss' only with a well-tested allowlist.",
    check: 'Verify tools.exec.ask in openclaw.json.',
    docRef: '/tool-security#ask-modes',
    options: { values: ['off', 'on-miss', 'always'], recommended: 'always' },
  },
  {
    id: 'exec-3',
    title: 'Exec Allowlist',
    category: 'exec',
    configPath: 'tools.exec.allowlist',
    severity: 'high',
    risk: 'An empty or overly broad allowlist defeats the purpose of allowlist security mode. Piped commands are parsed per-segment.',
    recommendation: "Define specific command patterns. Keep patterns narrow (e.g., 'git status') rather than broad. Backtick and $() substitution are always rejected.",
    check: 'Review tools.exec.allowlist entries for overly permissive patterns.',
    docRef: '/tool-security#allowlist-evaluation',
  },
  {
    id: 'exec-4',
    title: 'Safe Bins Configuration',
    category: 'exec',
    configPath: 'tools.exec.safeBins',
    severity: 'medium',
    risk: 'Adding interpreters (python, node) to safe bins lets them execute arbitrary code, bypassing exec security entirely.',
    recommendation: 'Only add data-transformation binaries (jq, cut, head, tail). Never add interpreters without strict profiled constraints.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "tools.exec.safe_bins_interpreter_unprofiled")\'',
    auditCheckId: 'tools.exec.safe_bins_interpreter_unprofiled',
    docRef: '/tool-security#_5-safebins-and-safebinprofiles',
  },
  {
    id: 'exec-5',
    title: 'apply_patch workspaceOnly',
    category: 'exec',
    configPath: 'tools.exec.applyPatch.workspaceOnly',
    severity: 'high',
    risk: 'When false, apply_patch can write to any filesystem location, enabling overwriting system files, injecting SSH keys, or modifying cron jobs.',
    recommendation: 'Keep set to true (default). Setting to false is flagged as a dangerous config flag.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "config.insecure_or_dangerous_flags")\'',
    auditCheckId: 'config.insecure_or_dangerous_flags',
    docRef: '/tool-security#_4-exec-approval-system',
  },

  // ═══════════════════════════════════════════
  // Docker Sandboxing
  // ═══════════════════════════════════════════
  {
    id: 'sbx-1',
    title: 'Sandbox Mode',
    category: 'sandbox',
    configPath: 'tools.sandbox.mode',
    severity: 'critical',
    risk: 'Without sandboxing, agents execute directly on the host with full filesystem and network access. A prompt-injected agent can read credentials or install backdoors.',
    recommendation: "Set to 'all' so every agent runs in a Docker container. Use 'non-main' as a minimum for multi-user deployments.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "sandbox.docker_config_mode_off")\'',
    auditCheckId: 'sandbox.docker_config_mode_off',
    docRef: '/tool-security#sandbox-modes',
    options: { values: ['off', 'non-main', 'all'], recommended: 'all' },
  },
  {
    id: 'sbx-2',
    title: 'Sandbox Scope',
    category: 'sandbox',
    configPath: 'tools.sandbox.scope',
    severity: 'medium',
    risk: "A 'shared' scope means all users share one container. A compromised session can read another user's files or data inside the container.",
    recommendation: "Set to 'session' so each user gets a fresh, isolated container.",
    check: 'Verify tools.sandbox.scope in openclaw.json.',
    docRef: '/tool-security#sandbox-scope',
    options: { values: ['session', 'agent', 'shared'], recommended: 'session' },
  },
  {
    id: 'sbx-3',
    title: 'Workspace Access',
    category: 'sandbox',
    configPath: 'tools.sandbox.workspaceAccess',
    severity: 'high',
    risk: 'Read-write workspace access lets a sandboxed agent modify host files, potentially poisoning SOUL.md or bootstrap files for future sessions.',
    recommendation: "Set to 'none' unless the agent explicitly needs file access. Use 'ro' for read-only agents.",
    check: 'Verify tools.sandbox.workspaceAccess in openclaw.json.',
    docRef: '/tool-security#workspace-access',
    options: { values: ['none', 'ro', 'rw'], recommended: 'none' },
  },
  {
    id: 'sbx-4',
    title: 'Bind Mount Validation',
    category: 'sandbox',
    configPath: 'tools.sandbox.bindMounts',
    severity: 'critical',
    risk: 'Mounting sensitive host paths (/etc, /proc, /sys, /dev, /root, docker.sock) gives the agent direct access to host configuration or the Docker daemon.',
    recommendation: 'Never mount sensitive paths. OpenClaw blocks /etc, /proc, /sys, /dev, /root, /boot, /run, docker.sock by default.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "sandbox.dangerous_bind_mount")\'',
    auditCheckId: 'sandbox.dangerous_bind_mount',
    docRef: '/tool-security#bind-mount-validation',
  },
  {
    id: 'sbx-5',
    title: 'Network Isolation',
    category: 'sandbox',
    configPath: 'tools.sandbox.network',
    severity: 'critical',
    risk: 'Network access from a sandboxed container lets a compromised agent exfiltrate data or download malicious payloads.',
    recommendation: "Leave the default '--network none'. Only override when the workflow explicitly requires network access. Never use 'host' mode.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "sandbox.dangerous_network_mode")\'',
    auditCheckId: 'sandbox.dangerous_network_mode',
    docRef: '/tool-security#docker-container-security-defaults',
    options: { values: ['none', 'bridge', 'host'], recommended: 'none' },
  },
  {
    id: 'sbx-6',
    title: 'Capability Dropping',
    category: 'sandbox',
    configPath: 'tools.sandbox.capDrop',
    severity: 'high',
    risk: 'Retaining Linux capabilities (CAP_SYS_ADMIN, CAP_NET_RAW) enables privilege escalation, network sniffing, or container escape.',
    recommendation: "Keep '--cap-drop ALL' (default). The '--security-opt no-new-privileges' flag is hardcoded and cannot be disabled.",
    check: "Verify capDrop is not overridden to empty. Confirm no-new-privileges via 'docker inspect'.",
    docRef: '/tool-security#docker-container-security-defaults',
  },
  {
    id: 'sbx-7',
    title: 'Seccomp and AppArmor Profiles',
    category: 'sandbox',
    configPath: 'tools.sandbox.seccomp',
    severity: 'critical',
    risk: "Setting seccomp or AppArmor to 'unconfined' disables kernel-level syscall restrictions, allowing arbitrary system calls.",
    recommendation: "Never set to 'unconfined'. Use Docker default seccomp profile or a custom restrictive profile.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "sandbox.dangerous_seccomp_profile" or .id == "sandbox.dangerous_apparmor_profile")\'',
    auditCheckId: 'sandbox.dangerous_seccomp_profile',
    docRef: '/tool-security#docker-container-security-defaults',
  },
  {
    id: 'sbx-8',
    title: 'Environment Variable Sanitization',
    category: 'sandbox',
    configPath: 'tools.sandbox.envStrict',
    severity: 'high',
    risk: 'API keys, bot tokens, and cloud credentials passed into the container can be read by agent-executed code and exfiltrated.',
    recommendation: 'Rely on the default blocked-variable list. Enable strict mode to whitelist only LANG, PATH, HOME, USER, SHELL, TERM, TZ, NODE_ENV.',
    check: "Review env vars in running containers with 'docker inspect'. Verify sensitive variables are absent.",
    docRef: '/tool-security#environment-variable-sanitization',
  },

  // ═══════════════════════════════════════════
  // Elevated Mode
  // ═══════════════════════════════════════════
  {
    id: 'elev-1',
    title: 'Elevated Mode Gate',
    category: 'elevated',
    configPath: 'tools.elevated.enabled',
    severity: 'critical',
    risk: 'Enabling elevated mode allows agents to break out of the sandbox and execute commands directly on the host.',
    recommendation: "Keep disabled (default: false). When enabled, combine with tight allowFrom restrictions and use '/elevated on' (not '/elevated full').",
    check: 'Verify tools.elevated.enabled is false in openclaw.json.',
    docRef: '/tool-security#_7-elevated-mode',
  },
  {
    id: 'elev-2',
    title: 'Elevated AllowFrom',
    category: 'elevated',
    configPath: 'tools.elevated.allowFrom.<provider>',
    severity: 'critical',
    risk: "A wildcard ('*') in allowFrom lets any sender activate host execution. In a multi-user deployment, any paired user can run arbitrary commands on the host.",
    recommendation: "List explicit sender IDs per provider. Never use ['*']. Keep the list as short as possible.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "tools.elevated.allowFrom.*.wildcard")\'',
    auditCheckId: 'tools.elevated.allowFrom.*.wildcard',
    docRef: '/tool-security#access-gates',
  },
  {
    id: 'elev-3',
    title: 'Elevated Execution Levels',
    category: 'elevated',
    configPath: 'tools.elevated.level',
    severity: 'high',
    risk: "'/elevated full' removes all approval gates, giving unrestricted shell access on the host.",
    recommendation: "Use '/elevated on' (host + approval) as maximum. Never '/elevated full' for untrusted deployments.",
    check: 'Verify agents.defaults.elevatedDefault is not set to a permissive level.',
    docRef: '/tool-security#elevation-levels',
    options: { values: ['off', 'on', 'ask', 'full'], recommended: 'off' },
  },

  // ═══════════════════════════════════════════
  // Hooks & Webhooks
  // ═══════════════════════════════════════════
  {
    id: 'hook-1',
    title: 'Hook Token',
    category: 'hooks',
    configPath: 'hooks.token',
    severity: 'high',
    risk: 'A short or missing hook token allows unauthorized external systems to trigger agent turns via the webhook endpoint.',
    recommendation: 'Set to a unique, random string of at least 24 characters. Uses timing-safe SHA-256 comparison.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "hooks.token_too_short")\'',
    auditCheckId: 'hooks.token_too_short',
    docRef: '/network-security#_6-hooks-security',
  },
  {
    id: 'hook-2',
    title: 'Token Reuse Prevention',
    category: 'hooks',
    configPath: 'hooks.token',
    severity: 'critical',
    risk: 'If the hooks token matches the gateway token, a leak of either compromises both layers simultaneously.',
    recommendation: 'Ensure hooks.token differs from gateway.auth.token. The gateway refuses to start if they match.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "hooks.token_reuse_gateway_token")\'',
    auditCheckId: 'hooks.token_reuse_gateway_token',
    docRef: '/network-security#token-constraints',
  },
  {
    id: 'hook-3',
    title: 'Session Key Injection',
    category: 'hooks',
    configPath: 'hooks.allowRequestSessionKey',
    severity: 'high',
    risk: 'When enabled, external callers can inject messages into arbitrary sessions or create sessions with attacker-chosen keys.',
    recommendation: 'Keep set to false (default). If enabled, always configure allowedSessionKeyPrefixes.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "hooks.request_session_key_enabled")\'',
    auditCheckId: 'hooks.request_session_key_enabled',
    docRef: '/network-security#session-key-controls',
  },
  {
    id: 'hook-4',
    title: 'Session Key Prefixes',
    category: 'hooks',
    configPath: 'hooks.allowedSessionKeyPrefixes',
    severity: 'high',
    risk: 'Without prefix constraints, external callers can target any session key pattern, including internal DM and group sessions.',
    recommendation: 'If allowRequestSessionKey is true, always set allowedSessionKeyPrefixes. Prefixes are case-insensitive.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "hooks.request_session_key_prefixes_missing")\'',
    auditCheckId: 'hooks.request_session_key_prefixes_missing',
    docRef: '/network-security#session-key-controls',
  },
  {
    id: 'hook-5',
    title: 'Unsafe External Content',
    category: 'hooks',
    configPath: 'hooks.allowUnsafeExternalContent',
    severity: 'high',
    risk: 'When true, external content is passed to the agent without sanitization, enabling prompt injection, homoglyph spoofing, and marker-spoofing attacks.',
    recommendation: 'Keep false (default). External content gets boundary markers, security warnings, and homoglyph detection.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "config.insecure_or_dangerous_flags")\'',
    auditCheckId: 'config.insecure_or_dangerous_flags',
    docRef: '/network-security#external-content-handling',
  },

  // ═══════════════════════════════════════════
  // Plugins & Extensions
  // ═══════════════════════════════════════════
  {
    id: 'plug-1',
    title: 'Plugin Allowlist',
    category: 'plugins',
    configPath: 'plugins.allow',
    severity: 'critical',
    risk: 'Without an allowlist, any discovered plugin loads in-process with full gateway privileges, including access to all config secrets.',
    recommendation: 'Set plugins.allow to an explicit array of trusted plugin IDs.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "plugins.extensions_no_allowlist")\'',
    auditCheckId: 'plugins.extensions_no_allowlist',
    docRef: '/plugins-extensions#_2-plugin-allowlist',
  },
  {
    id: 'plug-2',
    title: 'Plugin Deny List',
    category: 'plugins',
    configPath: 'plugins.deny',
    severity: 'high',
    risk: 'Without a deny list, there is no mechanism to block a specific known-bad plugin. Deny takes precedence over allow.',
    recommendation: 'Maintain a plugins.deny array of plugin IDs that should never load.',
    check: 'Verify plugins.deny in openclaw.json.',
    docRef: '/plugins-extensions#_2-plugin-allowlist',
  },
  {
    id: 'plug-3',
    title: 'Plugin HTTP Route Auth',
    category: 'plugins',
    configPath: '(plugin-implemented)',
    severity: 'critical',
    risk: 'Plugin HTTP routes are dispatched WITHOUT gateway auth. Only /api/channels/* routes are auto-gated.',
    recommendation: 'Ensure every plugin implements its own authentication on HTTP routes. Audit plugin source.',
    check: 'openclaw security audit --deep --json | jq \'.checks[] | select(.id | startswith("plugins."))\'',
    docRef: '/plugins-extensions#_4-plugin-http-routes-no-gateway-auth',
  },
  {
    id: 'plug-4',
    title: 'Plugin Code Scanning',
    category: 'plugins',
    configPath: '(automated)',
    severity: 'high',
    risk: 'Plugins run in-process with no isolation. Dangerous code patterns are warn-only during install and never block loading.',
    recommendation: "Run 'openclaw security audit --deep' to scan all installed plugins. Review critical findings before production.",
    check: 'openclaw security audit --deep --json | jq \'.checks[] | select(.id == "plugins.code_safety")\'',
    auditCheckId: 'plugins.code_safety',
    docRef: '/plugins-extensions#_5-plugin-code-safety-scanning',
  },
  {
    id: 'plug-5',
    title: 'npm Lifecycle Script Risks',
    category: 'plugins',
    configPath: '(install-time)',
    severity: 'high',
    risk: 'Plugin installation via npm executes preinstall/postinstall lifecycle scripts from all dependencies. A malicious dependency runs arbitrary code on the host.',
    recommendation: "Pin exact versions. Consider 'npm install --ignore-scripts' and verifying manually.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "plugins.installs_unpinned_npm_specs")\'',
    auditCheckId: 'plugins.installs_unpinned_npm_specs',
    docRef: '/plugins-extensions#_6-npm-install-risks',
  },

  // ═══════════════════════════════════════════
  // Credentials & Secrets
  // ═══════════════════════════════════════════
  {
    id: 'cred-1',
    title: 'State Directory Permissions',
    category: 'credentials',
    configPath: '~/.openclaw/',
    severity: 'critical',
    risk: 'World-writable or group-writable state directory lets other OS users read or modify gateway config, credentials, and session transcripts.',
    recommendation: "Set to mode 0o700. Run 'openclaw security audit --fix' to auto-remediate.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "fs.state_dir.perms_world_writable")\'',
    auditCheckId: 'fs.state_dir.perms_world_writable',
    docRef: '/credentials-secrets#_2-file-permission-model',
  },
  {
    id: 'cred-2',
    title: 'Config File Permissions',
    category: 'credentials',
    configPath: '~/.openclaw/openclaw.json',
    severity: 'critical',
    risk: 'A world-readable config file exposes gateway tokens, hook tokens, API keys, and channel credentials.',
    recommendation: "Set to mode 0o600. Run 'openclaw security audit --fix' to auto-remediate.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "fs.config.perms_writable")\'',
    auditCheckId: 'fs.config.perms_writable',
    docRef: '/credentials-secrets#_2-file-permission-model',
  },
  {
    id: 'cred-3',
    title: 'Credential File Permissions',
    category: 'credentials',
    configPath: '~/.openclaw/credentials/',
    severity: 'critical',
    risk: 'Credential files (WhatsApp creds, pairing allowlists, OAuth tokens) with lax permissions expose authentication material.',
    recommendation: "Set credentials/ to 0o700 and all JSON files to 0o600. Run 'openclaw security audit --fix'.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "fs.credentials_dir.perms_writable")\'',
    auditCheckId: 'fs.credentials_dir.perms_writable',
    docRef: '/credentials-secrets#_2-file-permission-model',
  },
  {
    id: 'cred-4',
    title: 'Device Keypair Permissions',
    category: 'credentials',
    configPath: '~/.openclaw/identity/device.json',
    severity: 'critical',
    risk: 'The Ed25519 private key file — if readable by others, an attacker can impersonate the device and bypass device auth.',
    recommendation: "Set to mode 0o600. Run 'openclaw security audit --fix'. Never share this file between hosts.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "fs.auth_profiles.perms_writable")\'',
    auditCheckId: 'fs.auth_profiles.perms_writable',
    docRef: '/credentials-secrets#_2-file-permission-model',
  },
  {
    id: 'cred-5',
    title: 'Log Redaction Mode',
    category: 'credentials',
    configPath: 'logging.redactSensitive',
    severity: 'high',
    risk: 'With redaction off, API keys, tokens, passwords, and PEM blocks appear in plain text in tool output and status summaries.',
    recommendation: "Keep set to 'tools' (default). Masks 17 default patterns including ENV assignments, auth headers, and PEM blocks.",
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "logging.redact_off")\'',
    auditCheckId: 'logging.redact_off',
    docRef: '/credentials-secrets#_4-logging-redaction',
    options: { values: ['tools', 'off'], recommended: 'tools' },
  },
  {
    id: 'cred-6',
    title: 'Custom Redaction Patterns',
    category: 'credentials',
    configPath: 'logging.redactPatterns',
    severity: 'medium',
    risk: 'Custom redaction patterns REPLACE the 17 defaults. If set without including defaults, standard credential formats are no longer masked.',
    recommendation: 'When adding custom patterns, include all 17 default patterns alongside your additions.',
    check: 'Verify logging.redactPatterns includes default patterns if set.',
    docRef: '/credentials-secrets#_4-logging-redaction',
  },
  {
    id: 'cred-7',
    title: 'Disk Encryption',
    category: 'credentials',
    configPath: '(host-level)',
    severity: 'high',
    risk: 'Session transcripts can contain pasted secrets and file contents. Without disk encryption, physical access exposes all stored data.',
    recommendation: 'Enable full-disk encryption (FileVault, LUKS, BitLocker) on the gateway host.',
    check: "macOS: 'fdesetup status'. Linux: 'lsblk -o NAME,FSTYPE,MOUNTPOINT | grep crypt'.",
    docRef: '/credentials-secrets#_3-sensitive-data-on-disk',
  },

  // ═══════════════════════════════════════════
  // Agent Configuration
  // ═══════════════════════════════════════════
  {
    id: 'agent-1',
    title: 'Owner Identity Display',
    category: 'agent',
    configPath: 'commands.ownerDisplay',
    severity: 'medium',
    risk: 'Raw mode places sender IDs (phone numbers, usernames) directly in the system prompt and transcripts, creating PII exposure.',
    recommendation: "Set to 'hash' with commands.ownerDisplaySecret configured for HMAC-SHA256.",
    check: "Verify commands.ownerDisplay is 'hash' and ownerDisplaySecret is configured.",
    docRef: '/agent-configuration#_7-owner-identity',
    options: { values: ['raw', 'hash'], recommended: 'hash' },
  },
  {
    id: 'agent-2',
    title: 'Bootstrap File Injection',
    category: 'agent',
    configPath: 'agents.defaults.skipBootstrap',
    severity: 'medium',
    risk: 'Bootstrap files (AGENTS.md, TOOLS.md, USER.md) are injected into the system prompt with no sanitization. A user with workspace access can embed arbitrary instructions.',
    recommendation: 'Set skipBootstrap to true for agents in untrusted workspaces. Use bootstrapMaxChars to limit context flooding.',
    check: 'Verify agents.defaults.skipBootstrap for untrusted workspaces.',
    docRef: '/agent-configuration#_4-bootstrap-context-files',
  },
  {
    id: 'agent-3',
    title: 'Skill Loading Security',
    category: 'agent',
    configPath: 'agents.<id>.skills',
    severity: 'high',
    risk: 'Skills are natural-language executable instructions loaded from multiple discovery paths with no signing or integrity verification. Malicious repos can include auto-discovered project-local skills.',
    recommendation: "Audit all skill discovery paths. Don't operate agents in untrusted directories. Run 'openclaw security audit --deep' to scan.",
    check: 'openclaw security audit --deep --json | jq \'.checks[] | select(.id == "skills.code_safety")\'',
    auditCheckId: 'skills.code_safety',
    docRef: '/clawhub-skills-safety#_7-skill-security-model',
  },
  {
    id: 'agent-4',
    title: 'Plugin Prompt Hooks',
    category: 'agent',
    configPath: '(plugin-implemented)',
    severity: 'critical',
    risk: 'Plugins can replace the entire system prompt via before_prompt_build, downgrade the model via before_model_resolve, or redirect API calls to arbitrary endpoints.',
    recommendation: 'Only load trusted plugins. Audit source for before_prompt_build and before_model_resolve hooks.',
    check: 'openclaw security audit --deep --json | jq \'.checks[] | select(.id | startswith("plugins."))\'',
    docRef: '/agent-configuration#_6-plugin-prompt-hooks',
  },
  {
    id: 'agent-5',
    title: 'Model Selection',
    category: 'agent',
    configPath: 'agents.<id>.model',
    severity: 'high',
    risk: 'Small-parameter or legacy models are more susceptible to prompt injection. Per-agent selection can route agents to weaker models.',
    recommendation: 'Use the latest instruction-hardened model (e.g., Opus 4.6) for tool-enabled agents.',
    check: 'openclaw security audit --json | jq \'.checks[] | select(.id == "models.small_params" or .id == "models.weak_tier")\'',
    auditCheckId: 'models.small_params',
    docRef: '/agent-configuration#_9-per-agent-configuration-overrides',
  },
]

// Deployment profile presets
export interface DeploymentProfile {
  id: string
  title: string
  description: string
  notApplicable: string[] // control IDs to pre-set as N/A
}

export const profiles: DeploymentProfile[] = [
  {
    id: 'enterprise',
    title: 'Enterprise',
    description: 'Public-facing, multi-user, untrusted senders. All controls apply.',
    notApplicable: [],
  },
  {
    id: 'personal',
    title: 'Personal',
    description: 'Single-user, trusted network, personal use.',
    notApplicable: [
      'sess-2', 'sess-4', // identity links, multi-account
      'chan-5', 'chan-6', // group allowFrom, per-sender tools
      'chan-8', // pairing codes (single user)
    ],
  },
  {
    id: 'development',
    title: 'Development',
    description: 'Local only, testing and development.',
    notApplicable: [
      'net-3', 'net-4', 'net-5', 'net-6', 'net-7', // network exposure controls
      'sess-2', 'sess-4', // multi-user session controls
      'chan-1', 'chan-2', 'chan-3', 'chan-4', 'chan-5', 'chan-6', 'chan-7', 'chan-8', // all channel controls
      'hook-1', 'hook-2', 'hook-3', 'hook-4', 'hook-5', // all hooks
      'elev-2', // elevated allowFrom (single user)
      'cred-7', // disk encryption (dev machine)
    ],
  },
]
